---
Name: memberinvitationroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'invite//$Action/$ID': 'Mouseketeers\SilverstripeMemberInvitation\MemberInvitationController'
