mappings:
  MemberInvitationForm: Mouseketeers\SilverstripeMemberInvitation\MemberInvitationForm
  MemberInvitationFieldDetailForm_ItemRequest: Mouseketeers\SilverstripeMemberInvitation\MemberInvitationFieldDetailForm_ItemRequest
  MemberInvitationController: Mouseketeers\SilverstripeMemberInvitation\MemberInvitationController
  MemberInvitationSecurityAdminExtension: Mouseketeers\SilverstripeMemberInvitation\MemberInvitationSecurityAdminExtension
  MemberInvitationAcceptForm: Mouseketeers\SilverstripeMemberInvitation\MemberInvitationAcceptForm
  MemberInvitation: Mouseketeers\SilverstripeMemberInvitation\MemberInvitation
